### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by takeda** [python-zk/kazoo#746] opened 2024-02-25 21:13 UTC
## What would you like to be added

Support to use Kazoo in asyncio based python code.

## Why is this needed

AsyncIO became a first class citizen in python ecosystem and more and more applications are written with it in mind. It would be great if Kazoo could support it as well, especially that it does allow async commands already.

**Comment by StephenSorriaux** [comment] 2024-03-03 17:31
Hello,

Thank you for the issue.

Like you said, I think this would be a very nice addition too. An attempt has been made with https://github.com/python-zk/kazoo/pull/646 but, on my side, I am not very familiar developing for `asyncio` (I am just an user of this API) so I was not able to know if the proposed changes were *the way to go* and did not feel comfortable giving any feedback.

I can take some time to study how we should/could do it but if anyone in @python-zk/maintainers have some experiences developing for `asyncio` please feel free to shim in!
If you have any opinion about the proposed changes or some time to made a PR for this feature, please also feel free to do so!

**Comment by StephenSorriaux** [comment] 2024-03-08 19:54
Closing as duplicate of https://github.com/python-zk/kazoo/issues/185

**Closed** 2024-03-08 20:32 UTC
Labels: Enhancement

**Comment by jeffwidman** [comment] 2024-03-08 20:34
Closing using reason "duplicate" rather than reason "complete"... @StephenSorriaux not sure if you've seen but this is a nifty new feature GitHub offers and makes it quicker to skim issues in search results etc. 🎉

**Comment by StephenSorriaux** [comment] 2024-03-09 18:05
@jeffwidman I didn't notice, thank you for the tips!
